# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flowerSchool_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flowerSchool_MVVM
    pod 'SDWebImage'
    pod 'LGSideMenuController'
    pod 'Alamofire'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxRelay'
    pod 'RealmSwift'
    pod 'RxRealm'

end
